# Generated by Django 4.1.7 on 2023-03-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Card",
                "verbose_name_plural": "Cards",
                "db_table": "cards",
            },
        ),
    ]
